import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Contact</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="text-3xl bg-primary p-3">Contact</div>
    </div>
  );
}
