import Head from "next/head";

export default function Projects() {
  return (
    <div className="x-adj">
      <Head>
        <title>Projects</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="text-3xl bg-primary p-3">Projects</div>
    </div>
  );
}
