import Head from "next/head";
import userData from "../helper/data";

export default function Timeline() {
  return (
    <div className="x-adj">
      <Head>
        <title>Hrushi Kedar - Timeline</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="mt-4">
        <div className="grid grid-cols-1  max-w-xl mx-auto pt-20">
          {/* Experience card */}
          {userData.experience.map((exp, idx) => (
            <>
              <ExperienceCard
                key={idx}
                title={exp.title}
                desc={exp.desc}
                year={exp.year}
                company={exp.company}
                companyLink={exp.companyLink}
              />
              {idx === userData.experience.length - 1 ? null : (
                <div className="divider-container flex flex-col items-center -mt-2">
                  <div className="w-4 h-4 bg-green-500 rounded-full relative z-10">
                    <div className="w-4 h-4 bg-green-500 rounded-full relative z-10 animate-ping"></div>
                  </div>
                  <div className="w-1 h-24 bg-gray-200 dark:bg-gray-600 rounded-full -mt-2"></div>
                </div>
              )}
            </>
          ))}
        </div>
      </div>
      <div className="max-w-6xl mx-auto h-12"></div>
    </div>
  );
}

const ExperienceCard = ({ title, desc, year, company, companyLink }) => {
  return (
    <div className="relative border p-4 rounded-md shadow-xl bg-gray-800 mx-4">
      <h1 className="absolute -top-10 md:-left-10 md:-top-10 md:text-4xl text-3xl text-primary font-bold ">
        {year}
      </h1>
      <h1 className="font-semibold text-xl text-secondary">{title}</h1>
      <a href={companyLink} className="text-white">
        {company}
      </a>
      <p className="text-white my-2">{desc}</p>
    </div>
  );
};
